// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {fs} from '../models';

export function Execute(arg1:string):Promise<void>;

export function ListItems(arg1:string):Promise<fs.Result>;
