// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Execute(arg1) {
  return window['go']['main']['App']['Execute'](arg1);
}

export function ListItems(arg1) {
  return window['go']['main']['App']['ListItems'](arg1);
}
